version: "3.9"

services:
  web:
    build: docker/nginx
    ports:
      - "61080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    links:
      - php-fpm

  php-fpm:
    build: docker/php
    volumes:
      - ./:/var/www/html
      - ./log/php:/var/log/php

