<?php

class VenueSchedule extends TableObject
{
	public $id				= 0;
    public $name		    = '';
	public $week			= '';
	public $periodFrom	    = '';
	public $periodTo	    = '';
    public $validFrom      	= '';
    public $validEnd      	= '';
    public $sex	        	= '不限';
    public $minAge	        = 0;
    public $maxAge	        = 0;
	public $count           = 1;
	public $maxCount        = 1;
    public $exclude      	= '';

    protected function init($data)
    {
        if ( is_array( $data[ 'week' ] ) )
        {
            $data[ 'week' ] = implode(',', $data[ 'week' ] );
        }

        parent::init($data); // TODO: Change the autogenerated stub
    }
}

